# Python is call by Assignment  

 * if parameter is value -> call by value

 * if parameter is object -> call by reference

In [4]:
class car():
    w = 0;
    

In [13]:
car()
car.w = 1

print(car.w)

def test(a, b):
    a.w = 2
    b = 3

1


In [14]:
testb = 0
test(car, testb)

print(car.w, testb)

# in this case car is mutable object

# mutable   : list, dict, set, byte-array, user-defined class
# immutable : string, int, float, bool, tuple, range, bytes...

2 0


## Recursion for factorial function

In [21]:
def factorial(n):
    
    # check n is > 0
    if (n < 0):
        print("Error n < 0!!!")
        return None
    
    if (n <= 1):
        return 1
    else:
        result = n * factorial(n-1)
        return result

In [23]:
factorial(2.5)

3.75

# Function 

* 函式(Function)結構
* 函式(Function)參數
* 函式(Function) \*args、\**kwargs運算子
* 函式(Function)種類
* 函式(Function)變數範圍(Scope)

In [1]:
# 函式(Function)結構

def twoSum(a, b):
    return a + b

twoSum(8, 7)

15

### 函式(Function)參數(Argument) => a and b

Argument => a and b

Parameter => 8 and 7

In [5]:
# 關鍵字參數(Keyword Argument)

def twoSum(value1, value2):
    print(f"value1: {value1} \t value2: {value2}")
    return value1 + value2

twoSum(value2=8,  value1=7)

value1: 7 	 value2: 8


15

In [6]:
# 預設值參數(Default Argument)

def twoSum(value1=0, value2=0):
    print(f"value1: {value1} \t value2: {value2}")
    return value1 + value2

twoSum()

value1: 0 	 value2: 0


0

## 函式(Function) \*args、\**kwargs運算子

當我們要傳入大量的參數時，在函式上定義過多的參數名稱會讓程式碼的可讀性降低，這時候就可以使用 * 符號來將傳入參數進行打包

提供兩種打包型態:

    1. tuple => like list but immutable
    2. dict  => more convenient via using key and value

In [19]:
# Tuple 打包 (immutable input)
def app_log(*info):
    print(info)
    #info[1] = "change!!!" # error 'tuple' object does not support item assignment
    
app_log("apple", "banana", "cake", 4, 5.5, 6.78, 7, "8")

('apple', 'banana', 'cake', 4, 5.5, 6.78, 7, '8')


In [20]:
# dictionary 打包 (mutable input)
def app_log(**info):
    print(info)
    info["a"] = "change!!!"
    print(info)
    
x = "test"
app_log(a=x, b="banana", c="cake", d=4, e=5.5, f=6.78, g=7, h="8")

{'a': 'test', 'b': 'banana', 'c': 'cake', 'd': 4, 'e': 5.5, 'f': 6.78, 'g': 7, 'h': '8'}
{'a': 'change!!!', 'b': 'banana', 'c': 'cake', 'd': 4, 'e': 5.5, 'f': 6.78, 'g': 7, 'h': '8'}


In [21]:
print(x)

test


In [29]:
def app_log(info):
    print(info)
    info["a"] = "change!!!"
    print(info)

test = {"a":"test", "b":"banana", "c":"cake", "d":4, "e":5.5, "f":6.78, "g":7, "h":"8"}

print(test)
app_log(test)
print(test)

{'a': 'test', 'b': 'banana', 'c': 'cake', 'd': 4, 'e': 5.5, 'f': 6.78, 'g': 7, 'h': '8'}
{'a': 'test', 'b': 'banana', 'c': 'cake', 'd': 4, 'e': 5.5, 'f': 6.78, 'g': 7, 'h': '8'}
{'a': 'change!!!', 'b': 'banana', 'c': 'cake', 'd': 4, 'e': 5.5, 'f': 6.78, 'g': 7, 'h': '8'}
{'a': 'change!!!', 'b': 'banana', 'c': 'cake', 'd': 4, 'e': 5.5, 'f': 6.78, 'g': 7, 'h': '8'}


In [40]:
import numpy as np

# class + mutual / immutual testing

class MTFdata():
    
    def __init__(self, numCam=17, linePair=110):
        self.value_S = np.zeros(numCam)
        self.value_T = np.zeros(numCam)
        self.linePair = linePair
        
    def dataAdd1_inside(self):
        self.value_S = self.value_S + 1
        self.value_T = self.value_T + 1

def dataAdd1(data):
    if (isinstance(data, MTFdata)):
        data.value_S = data.value_S + 1
        data.value_T = data.value_T + 1
        
data = MTFdata()
print(data.value_S)

dataAdd1(data)
print(data.value_S)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [41]:
data.dataAdd1_inside()
print(data.value_S)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [5]:
def ajax(url, **user_settings):
    settings = {
        'method' : user_settings.get('method', 'no-find'),
        'contents' : user_settings.get('contents', 'no-find'),
        'datatype' : user_settings.get('datatype', 'no-find'),
        # 其他設定 ...
    }
    print('請求 {}'.format(url))
    print('設定 {}'.format(settings))

ajax('https://openhome.cc', method = 'POST', contents = 'book=python')


my_settings = {'method2' : 'POST2', 'contents2' : 'book=python'}
ajax('https://openhome.cc2', **my_settings)

請求 https://openhome.cc
設定 {'method': 'POST', 'contents': 'book=python', 'datatype': 'no-find'}
請求 https://openhome.cc2
設定 {'method': 'no-find', 'contents': 'no-find', 'datatype': 'no-find'}


# 如果argunment 是 mutable object 就可以改變

### 函式(Function) return

有return: return ans

沒return: return None <- python 自動預設

In [46]:
## scope of variable
x = 3

def add3(value):
    x = 20
    return value + x

add3(4)

24

In [47]:
print(x)

3


In [50]:
x = 3

def add3(value):
    global x
    x = 20
    return value + x

add3(4)

24

In [49]:
print(x)

20


### 補充 Python3.8: Positional-Only Parameters

想要某一個參數，一定要key-word or position方式進行引述傳遞，在定義參數列時可以使用 / or * 標示

/ 前的參數，不能採用關鍵字參數的形式來指定，對維護會有些幫助，因為你或許會有些參數名稱，不想成為API的一部份，就可以定義在 / 之前。

相對地，某些參數的值，也許想限定為只能以關鍵字參數形式指定，這時可以在參數列使用 * 來標示

定義參數列時，/ 與 * 可以併並存，/ 之後 * 之前的參數，可以使用位置參數或關鍵字參數形式指定

In [14]:
def POPtest(a, b, /, c, d, *, e, f):
    print('a =', a)
    print('b =', b)
    print('c =', c)
    print('d =', d)
    print('e =', e)
    print('f =', f)

In [15]:
POPtest(a=1, b=2, c=3, d=4, e=5, f=6)

TypeError: POPtest() got some positional-only arguments passed as keyword arguments: 'a, b'

In [16]:
## a, b只能放在1, 2位
POPtest(1, 2, c=3, d=4, e=5, f=6)

a = 1
b = 2
c = 3
d = 4
e = 5
f = 6


In [17]:
## e, f只能用key-word
POPtest(1, 2, c=3, d=4, 5, 6)

SyntaxError: positional argument follows keyword argument (<ipython-input-17-f8780df29870>, line 2)