In [1]:
import numpy as np

In [38]:
m = np.array([[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0]])
U = np.matrix(m)

In [39]:
U

matrix([[1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 1, 0, 0]])

In [40]:
U_H = U.getH()
U_H

matrix([[1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 1, 0, 0]])

In [41]:
U_H * U

matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [51]:
EigVal, EigState = np.linalg.eig(U)
EigVal

array([ 1., -1.,  1.,  1.])

In [52]:
EigState

matrix([[ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.70710678,  0.70710678,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ],
        [ 0.70710678, -0.70710678,  0.        ,  0.        ]])

In [59]:
a = np.array([[1, 0, 0, 0], [0, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
a = np.matrix(a)

b = np.array([[0, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]])
b = np.matrix(b)

sqrt_EigVal = a + 1j*b
sqrt_EigVal

matrix([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [61]:
ans = EigState*(sqrt_EigVal*EigState.getI())
ans

matrix([[1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
        [0. +0.j , 0.5+0.5j, 0. +0.j , 0.5-0.5j],
        [0. +0.j , 0. +0.j , 1. +0.j , 0. +0.j ],
        [0. +0.j , 0.5-0.5j, 0. +0.j , 0.5+0.5j]])

In [62]:
ans*ans

matrix([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j]])

In [30]:
s = np.array([[1, 0, 0, 0], [0, 0.5, 0.5, 0], [0, 0.5, 0.5, 0], [0, 0, 0, 1]])
S = np.matrix(s)

js = np.array([[0, 0, 0, 0], [0, 0.5, -0.5, 0], [0, -0.5, 0.5, 0], [0, 0, 0, 0]])
SWAP = S + 1j*js
SWAP

matrix([[1. +0.j , 0. +0.j , 0. +0.j , 0. +0.j ],
        [0. +0.j , 0.5+0.5j, 0.5-0.5j, 0. +0.j ],
        [0. +0.j , 0.5-0.5j, 0.5+0.5j, 0. +0.j ],
        [0. +0.j , 0. +0.j , 0. +0.j , 1. +0.j ]])

In [37]:
SS = SWAP*SWAP
SS

matrix([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])